---
- hosts: lb
  become: true
  tasks:
    - service:
        name: nginx
        state: stopped

- hosts: app
  become: true
  tasks:
    - service:
        name: apache2
        state: stopped

- hosts: db
  become: true
  tasks:
    - service:
        name: mysql
        state: restarted

- hosts: app
  become: true
  tasks:
    - service:
        name: apache2
        state: started

- hosts: lb
  become: true
  tasks:
    - service:
        name: nginx
        state: started
